name: ucad-macos
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy=1.22
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - pillow
  - opencv
  - imageio
  - yaml
  - tqdm
  - grpcio==1.47.0
  - pip
  - pip:
    - absl-py==1.2.0
    - blessings==1.7
    - cachetools==5.2.0
    - click==8.1.3
    - easydict==1.10
    - efficientnet-pytorch==0.7.1
    - einops==0.6.1
    - faiss-cpu==1.7.2
    - fonttools==4.33.3
    - google-auth==2.9.1
    - google-auth-oauthlib==0.4.6
    - idna==3.3
    - imgaug==0.4.0
    - ipython==8.6.0
    - joblib==1.1.0
    - kornia==0.6.8
    - markdown==3.4.1
    - networkx==2.8.4
    - oauthlib==3.2.0
    - packaging==21.3
    - plotly==5.11.0
    - protobuf==3.19.6
    - psutil==5.9.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygments==2.13.0
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pywavelets==1.3.0
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - shapely==1.8.2
    - tabulate==0.9.0
    - tenacity==8.1.0
    - tensorboard==2.9.1
    - tensorboardx==2.5.1
    - timm==0.6.7
    - torch==1.13.1
    - torchaudio==0.13.1
    - torchvision==0.14.1
    - traitlets==5.5.0
    - urllib3==1.26.10
    - zipp==3.8.1
